version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 2727:27017
    networks:
      - node_network
    volumes:
      - mongo_data:/data/db
  node:
    build: .
    container_name: express
    ports:
      - 3001:3001
    depends_on:
      - mongo
    environment:
      - NAME=Nauval
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - WAIT_HOSTS=mongo:27017
    networks:
      - node_network
    volumes:
      - .:/app

networks:
  node_network:

volumes:
  mongo_data:
